/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginLayoutImport } from './routes/_loginLayout'
import { Route as HomeLayoutImport } from './routes/_home-layout'
import { Route as HomeLayoutIndexImport } from './routes/_home-layout.index'
import { Route as LoginLayoutLoginImport } from './routes/_loginLayout.login'
import { Route as HomeLayoutCollectionsImport } from './routes/_home-layout.collections'

// Create/Update Routes

const LoginLayoutRoute = LoginLayoutImport.update({
  id: '/_loginLayout',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutRoute = HomeLayoutImport.update({
  id: '/_home-layout',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutIndexRoute = HomeLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const LoginLayoutLoginRoute = LoginLayoutLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LoginLayoutRoute,
} as any)

const HomeLayoutCollectionsRoute = HomeLayoutCollectionsImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => HomeLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home-layout': {
      id: '/_home-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_loginLayout': {
      id: '/_loginLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LoginLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_home-layout/collections': {
      id: '/_home-layout/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof HomeLayoutCollectionsImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_loginLayout/login': {
      id: '/_loginLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLayoutLoginImport
      parentRoute: typeof LoginLayoutImport
    }
    '/_home-layout/': {
      id: '/_home-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeLayoutIndexImport
      parentRoute: typeof HomeLayoutImport
    }
  }
}

// Create and export the route tree

interface HomeLayoutRouteChildren {
  HomeLayoutCollectionsRoute: typeof HomeLayoutCollectionsRoute
  HomeLayoutIndexRoute: typeof HomeLayoutIndexRoute
}

const HomeLayoutRouteChildren: HomeLayoutRouteChildren = {
  HomeLayoutCollectionsRoute: HomeLayoutCollectionsRoute,
  HomeLayoutIndexRoute: HomeLayoutIndexRoute,
}

const HomeLayoutRouteWithChildren = HomeLayoutRoute._addFileChildren(
  HomeLayoutRouteChildren,
)

interface LoginLayoutRouteChildren {
  LoginLayoutLoginRoute: typeof LoginLayoutLoginRoute
}

const LoginLayoutRouteChildren: LoginLayoutRouteChildren = {
  LoginLayoutLoginRoute: LoginLayoutLoginRoute,
}

const LoginLayoutRouteWithChildren = LoginLayoutRoute._addFileChildren(
  LoginLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof LoginLayoutRouteWithChildren
  '/collections': typeof HomeLayoutCollectionsRoute
  '/login': typeof LoginLayoutLoginRoute
  '/': typeof HomeLayoutIndexRoute
}

export interface FileRoutesByTo {
  '': typeof LoginLayoutRouteWithChildren
  '/collections': typeof HomeLayoutCollectionsRoute
  '/login': typeof LoginLayoutLoginRoute
  '/': typeof HomeLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_home-layout': typeof HomeLayoutRouteWithChildren
  '/_loginLayout': typeof LoginLayoutRouteWithChildren
  '/_home-layout/collections': typeof HomeLayoutCollectionsRoute
  '/_loginLayout/login': typeof LoginLayoutLoginRoute
  '/_home-layout/': typeof HomeLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/collections' | '/login' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/collections' | '/login' | '/'
  id:
    | '__root__'
    | '/_home-layout'
    | '/_loginLayout'
    | '/_home-layout/collections'
    | '/_loginLayout/login'
    | '/_home-layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeLayoutRoute: typeof HomeLayoutRouteWithChildren
  LoginLayoutRoute: typeof LoginLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  HomeLayoutRoute: HomeLayoutRouteWithChildren,
  LoginLayoutRoute: LoginLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_home-layout",
        "/_loginLayout"
      ]
    },
    "/_home-layout": {
      "filePath": "_home-layout.tsx",
      "children": [
        "/_home-layout/collections",
        "/_home-layout/"
      ]
    },
    "/_loginLayout": {
      "filePath": "_loginLayout.tsx",
      "children": [
        "/_loginLayout/login"
      ]
    },
    "/_home-layout/collections": {
      "filePath": "_home-layout.collections.tsx",
      "parent": "/_home-layout"
    },
    "/_loginLayout/login": {
      "filePath": "_loginLayout.login.tsx",
      "parent": "/_loginLayout"
    },
    "/_home-layout/": {
      "filePath": "_home-layout.index.tsx",
      "parent": "/_home-layout"
    }
  }
}
ROUTE_MANIFEST_END */
